### ISSUE TITLE
Error running sample dataset

### ISSUE THREAD

**Issue by Anto007** [christophertbrown/iRep#16]
Hi Chris,

I'm getting the below error when I try to run your sample dataset. I'm using virtualenv to switch between python versions. Any help here would be highly appreciated.

(ENV) antonycp@kw12957:~$ iRep -f /home/antonycp/Downloads/l_gasseri.fna -s /home/antonycp/Downloads/l_gasseri.fna-vs-l_gasseri_sample2-shrunk.sam -o /home/antonycp/Downloads/test.iRep
Traceback (most recent call last):
  File "/home/antonycp/ENV/bin/iRep", line 73, in <module>
    thresholds, args['no_gc_correction'], args['t'])
  File "/home/antonycp/ENV/lib/python3.6/site-packages/iRep/iRep.py", line 976, in iRep
    genomes, id2g = parse_genomes_fa(fastas, mappings)
  File "/home/antonycp/ENV/lib/python3.6/site-packages/iRep/iRep.py", line 916, in parse_genomes_fa
    for seq in parse_fasta(genome): 
  File "/home/antonycp/ENV/lib/python3.6/site-packages/iRep/fasta.py", line 19, in iterate_fasta
    sequence, formatted = parse_fasta(line, sequence, length)
  File "/home/antonycp/ENV/lib/python3.6/site-packages/iRep/fasta.py", line 32, in parse_fasta
    sequence[1].append(line.replace(' ', ''))
IndexError: list index out of range

**Comment by AhHua** [comment]
Hi Anto,

I know this is closed, but I am having the same error here. 
May I know what should I do to fix this?

Thank you very much. 

Yangyang

**Comment by lalalagartija** [comment]
same here and I tried bPTR on 2 different computers
